### ISSUE TITLE
task list

### ISSUE THREAD

**Issue by kiote** [kiote/kiote.github.io#1]
- [x] a task list item
- [x] list syntax required
- [ ] normal **formatting**, @mentions, #1 refs
- [ ] incomplete
- [x] completed
